version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "BooksTest"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1255x333bnfw2"
s3_prefix = "BooksTest"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
